# Generated by Django 3.1.2 on 2020-10-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_remove_user_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
